// An array of motivational quotes to be displayed on the screensaver.
export const MOTIVATIONAL_QUOTES: string[] = [
  "Stay focused.",
  "One step at a time.",
  "The secret of getting ahead is getting started.",
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Push yourself, because no one else is going to do it for you.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Do something today that your future self will thank you for.",
  "Don't watch the clock; do what it does. Keep going.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do what is right, not what is easy.",
  "The key to success is to focus on goals, not obstacles.",
  "The expert in anything was once a beginner.",
  "Your limitation—it's only your imagination.",
  "Great things never come from comfort zones.",
  "Success doesn't just find you. You have to go out and get it.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Strive for progress, not perfection.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Doubt kills more dreams than failure ever will.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "The best way to predict the future is to create it.",
  "You are the master of your destiny.",
  "Act as if what you do makes a difference. It does.",
  "The mind is everything. What you think you become.",
  "An obstacle is often a stepping stone.",
  "Don't be afraid to give up the good to go for the great.",
  "Either you run the day, or the day runs you.",
  "Small daily improvements are the key to staggering long-term results.",
  "You don't have to be great to start, but you have to start to be great.",
  "Focus on being productive instead of busy.",
  "The successful warrior is the average man, with laser-like focus.",
  "Discipline is the bridge between goals and accomplishment.",
  "There is no substitute for hard work.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Perseverance is failing 19 times and succeeding the 20th.",
  "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
  "If you want to lift yourself up, lift up someone else.",
  "You miss 100% of the shots you don’t take.",
  "The only person you are destined to become is the person you decide to be.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Fall seven times and stand up eight."
];
